# Generated by Django 5.2.5 on 2025-09-01 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seekerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='quick_apply_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Lista de aptitudini separate prin virgule'),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seekerprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
