# Generated by Django 5.2.5 on 2025-08-27 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobquestion_savedjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='flagged_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='job',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'În așteptare'), ('approved', 'Aprobat'), ('rejected', 'Respins')], default='approved', max_length=20),
        ),
        migrations.CreateModel(
            name='JobReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('duplicate', 'Duplicate'), ('contact_info', 'Date contact în anunț'), ('scam', 'Înșelătorie'), ('other', 'Alt motiv')], max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jobs.job')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
