# Generated by Django 5.2.5 on 2025-08-26 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, null=True, verbose_name='Scrisoare de intenție')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/%Y/%m/', verbose_name='CV')),
                ('status', models.CharField(choices=[('submitted', 'Trimisă'), ('viewed', 'Vizualizată'), ('interview', 'Interviu'), ('offer', 'Ofertă'), ('rejected', 'Respinsă')], default='submitted', max_length=20, verbose_name='Stare')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job', verbose_name='Job')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Candidat')),
            ],
            options={
                'verbose_name': 'Aplicație',
                'verbose_name_plural': 'Aplicații',
                'ordering': ['-created_at'],
                'unique_together': {('job', 'seeker')},
            },
        ),
    ]
